### ISSUE TITLE
openjdk的优化支持

### ISSUE THREAD

**Issue by haowuge** [loongson/jdk17u#7]
您好，我看这次发布会JAVA是解释器级的支持，带优化级的Java是否有计划推送给上游，是否有时间表？谢谢

**Comment by theaoqi** [comment]
是有计划推送给上游的。因为一些可控的和不可控的相关因素较多，具体时间表还无法给出，但是可以肯定的是龙芯也非常希望将该工作贡献给上游，我们正在开展相关工作。

感谢您的关注！
